config/routes.rb
Rails.application.routes.draw do
  root "home#blog"
  resources :galeries
  resources :admins
  resources :modalidades
  resources :professors
  resources :atleta
  # devise_for :users
  devise_for :users, skip: [:registrations]
  as :user do
    # root "home#index"
    get "amif" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/home', to: 'home#index'
  get 'profile/:id', to: 'admins#edit'
  post '/saveFrontPanel/:id', to: 'home#saveFrontPanel'
  get '/blog', to: 'home#blog'
  #resources :dailies
  get '/dailies', to: 'dailies#index'
  post '/dailies', to: 'dailies#create'
  get '/dailies/new', to: 'dailies#new'
  get 'edit/dailies', to: 'dailies#edit'
  get '/dailies/reports', to: 'dailies#reports'
  post '/dailies/reports', to: 'dailies#reports_list'
  # post '/dailies_chamada', to: 'dailies#chamada'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atletum.rb
class Atletum < ApplicationRecord
  validates :nome, presence: true
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :atletum
  belongs_to :modalidade
  belongs_to :professor
end

app/models/front_panel.rb
class FrontPanel < ApplicationRecord
end

app/models/galery.rb
class Galery < ApplicationRecord
  has_attached_file :imagem,
  :styles=>{:thumb => "100x100#",:small  => "150x150>", :medium => "300x300"}, :default_url=>"/assets/galery/default.jpg",
    :url=>"/assets/galery/:hash.:extension",:hash_secret=>"longSecretString"
  validates_attachment_content_type :imagem, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
  has_attached_file :imagem,
    :url=>"/modalidades/images/:hash.:extension",
    :hash_secret=>"longSecretString",
    :styles=> {original: "780x567>"}
  validates_attachment_content_type :imagem, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/professor.rb
class Professor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable#, :validatable

 has_attached_file :foto, :default_url=>"/assets/images/default.jpg",
   :url=>"/profile/images/:hash.:extension",:hash_secret=>"longSecretString"
 validates_attachment_content_type :foto, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atleta_helper.rb
module AtletaHelper
end

app/helpers/atletas_helper.rb
module AtletasHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/admins/_form.html.erb
<%= form_for(:admin, :url=>@url,:multipart=>true) do |f| %>
<%if @action=="edit"%>
<input name="_method" type="hidden" value="put" />
<%end%>
<div class="row">
  <div class="col s6">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="col s6">
    <%= f.label :sobrenome %>
    <%= f.text_field :sobrenome %>
  </div>
</div>
<div class="row">
  <div class="col s6">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="col s6">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
</div>
<div class="row">
  <div class="col s6">
    <%= f.label :modalidades_id %>
    <select name="admin[modalidades_id]">
      <%Modalidade.all.each do |m|%>
      <option value="<%=m.id%>" <%= "selected" if @action=="edit" && m.id== admin.modalidades_id%>><%=m.nome%></option>
      <%end%>
    </select>
  </div>
  <div class="col s6">
    <div class="file-field input-field">
      <div class="btn">
        <span>Anexar foto</span>
        <%=f.file_field :foto%>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
</div>
  <div class="field">
    <%if @action=="edit"%>
    <%= f.hidden_field :user_type,:value=>admin.user_type%>
    <%else%>
    <%= f.hidden_field :user_type, value: 0 %>
    <%end%>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn waves waves-effect"%>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div class="container">
<h1>Editar usuário</h1>

<%= render 'form', admin: @admin %>
</div>

app/views/admins/index.html.erb
<div class="container">
  <h1>Usuários</h1>
  <table class="bordered">
    <thead>
      <tr>
        <th>Foto</th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Email</th>
        <th>Modalidades</th>
        <th>Nível de usuário</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @admins.each do |admin| %>
        <tr>
          <td style="width: 70px"><img src="<%=admin.foto%>" width="50%"></td>
          <td><%= admin.nome %></td>
          <td><%= admin.sobrenome %></td>
          <td><%= admin.email %></td>
          <td><%= Modalidade.find_by_id(admin.modalidades_id).nome %></td>
          <td><%= @user_type[admin.user_type] %></td>
          <td><a href="/admins/<%=admin.id%>/edit">Editar</a></td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="fixed-action-btn vertical ">
    <a href="/admins/new" class="btn-floating btn-large waves-effect waves-light green right"><i class="material-icons">add</i></a>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container">
<%= link_to 'Voltar', '/admins'%>
<h1>Novo usuário</h1>
<%=render 'form'%>
</div>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @admin.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @admin.sobrenome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Modalidades:</strong>
  <%= @admin.modalidades_id %>
</p>

<p>
  <strong>User type:</strong>
  <%= @admin.user_type %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amif</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/stylesheet/animate.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style media="screen">
    body{
      background-size: contain;
      background-position: center;
    }
  </style>
  <body>
    <% if user_signed_in? %>
    <!-- SIDE MENU LATERAL-->
    <ul id="slide-out" class="side-nav">
      <li>
        <div class="userView">
        <div class="background">
        </div>
          <a href="/home"><center><img class="circle" src="<%=current_user.foto%>"></center></a>
          <a href="/home" align="center"><span class="black-text name"><%="#{current_user.nome} #{current_user.sobrenome}"%></span></a>
          <a href="/home" align="center"><span class="black-text email"><%=current_user.email%></span></a>
        </div>
      </li>
      <li><a href="/atleta"><i class="material-icons">directions_run</i>Atletas</a></li>
      <li>
        <a href="/dailies"><i class="material-icons">recent_actors</i>Lista de chamada</a>
      </li>
      <% if current_user.user_type == 1 %>
      <li><a href="/professors"><i class="material-icons">school</i>Professores</a></li>
      <li><a href="/modalidades"><i class="material-icons">style</i>Modalidades</a></li>
      <%end%>
      <% if current_user.user_type == 1%>
      <li><a href="/admins"><i class="material-icons">people</i>Usuários</a></li>
      <% end %>
      <li><a href="/galeries"><i class="material-icons">photo_library</i>Galeria</a></li>
      <li><div class="divider"></div></li>
      <li><a rel="nofollow" data-method="delete" href="/users/sign_out"><i class="material-icons">power_settings_new</i>Sair</a></li>
    </ul>
    <!-- FIM SIDE MENU LATERAL -->
    <!-- DROPDOWN MENU CONFIGURAÇÕES -->
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to 'Editar perfil', "/profile/#{current_user.id}"%></li>
      <li class="divider"></li>
      <li><%= link_to "Sair", destroy_user_session_path, method: :delete%></li>
    </ul>
    <nav>
      <div class="nav-wrapper">
        <a class="brand-logo logox" data-activates="slide-out"><i class="material-icons md-48">menu</i>AMIF</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#"><%= current_user.email %></a></li>
          <!-- <li><a href="badges.html">Components</a></li> -->
          <!-- Dropdown Trigger -->
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Configurações<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </nav>
    <!-- FIM DROPDOWN MENU CONFIGURAÇÕE -->
  <% end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield %>
    <% if notice %>
<script type="text/javascript">
Materialize.toast('<%= notice %>', 4000)
</script>
<% end %>
<% if alert %>
<script type="text/javascript">
Materialize.toast('<%= alert %>', 4000)
</script>
<% end %>
  </body>
</html>