config/routes.rb
Rails.application.routes.draw do
  root "home#blog"
  resources :galeries
  resources :admins
  resources :modalidades
  resources :professors
  resources :atleta
  # devise_for :users
  devise_for :users, skip: [:registrations]
  as :user do
    # root "home#index"
    get "amif" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/home', to: 'home#index'
  get 'profile/:id', to: 'admins#edit'
  post '/saveFrontPanel/:id', to: 'home#saveFrontPanel'
  get '/blog', to: 'home#blog'
  #resources :dailies
  get '/dailies', to: 'dailies#index'
  post '/dailies', to: 'dailies#create'
  get '/dailies/new', to: 'dailies#new'
  get 'edit/dailies', to: 'dailies#edit'
  get '/dailies/reports', to: 'dailies#reports'
  post '/dailies/reports', to: 'dailies#reports_list'
  # post '/dailies_chamada', to: 'dailies#chamada'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/galery.rb
class Galery < ApplicationRecord
  has_attached_file :imagem,
  :styles=>{:thumb => "100x100#",:small  => "150x150>", :medium => "300x300"}, :default_url=>"/assets/galery/default.jpg",
    :url=>"/assets/galery/:hash.:extension",:hash_secret=>"longSecretString"
  validates_attachment_content_type :imagem, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
  before_action :set_galery, only: [:show, :edit, :update, :destroy]

  # GET /galeries
  # GET /galeries.json
  def index
    @galeries = Galery.all.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /galeries/1
  # GET /galeries/1.json
  def show
    redirect_to "/" if current_user.user_type != 1
  end

  # GET /galeries/new
  def new
    redirect_to "/" if current_user.user_type != 1
    @galery = Galery.new if current_user.user_type == 1
  end

  # GET /galeries/1/edit
  def edit
    redirect_to "/" if current_user.user_type != 1
  end

  # POST /galeries
  # POST /galeries.json
  def create
    @galery = Galery.new(galery_params) if current_user.user_type == 1

    respond_to do |format|
      if @galery.save
        format.html { redirect_to @galery, notice: 'Galery was successfully created.' }
        format.json { render :show, status: :created, location: @galery }
      else
        format.html { render :new }
        format.json { render json: @galery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeries/1
  # PATCH/PUT /galeries/1.json
  def update
    if current_user.user_type == 1
      respond_to do |format|
        if @galery.update(galery_params)
          format.html { redirect_to @galery, notice: 'Galery was successfully updated.' }
          format.json { render :show, status: :ok, location: @galery }
        else
          format.html { render :edit }
          format.json { render json: @galery.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /galeries/1
  # DELETE /galeries/1.json
  def destroy
    @galery.destroy if current_user.user_type == 1
    respond_to do |format|
      format.html { redirect_to galeries_url, notice: 'Galery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galery
      @galery = Galery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galery_params
      params.require(:galery).permit(:imagem)
    end
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/views/galeries/_form.html.erb
<%= form_for(galery) do |f| %>
  <% if galery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(galery.errors.count, "error") %> prohibited this galery from being saved:</h2>
    </div>
  <% end %>
  <div class="row">
    <div class="col s3">
      <div class="file-field input-field">
          <div class="btn blue">
            <!-- <span>Anexar imagem</span> -->
            <i class="material-icons">camera_enhance</i>
            <%= f.file_field :imagem , required: "true"%>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
      </div>
    </div>
    <div class="col s4">
      <div class="actions">
        <%= f.submit "Enviar", class: "btn teal btn-large"%>
      </div>
    </div>
  </div>
<% end %>

app/views/galeries/edit.html.erb
<h1>Editing Galery</h1>

<%= render 'form', galery: @galery %>

<%= link_to 'Show', @galery %> |
<%= link_to 'Back', galeries_path %>

app/views/galeries/index.html.erb
<p id="notice"><%= notice %></p>
<style media="screen">
  .card{
    height: 350px;
  }
  .card-image  > img{
    height: 258px !important
  }
  .card-content{
    /*margin-top: 143px !important;*/
    position:absolute;
    bottom:0
  }
</style>
<h1>Galeria</h1>
    <div class="row">
    <% @galeries.each do |galery| %>
     <div class="col s4">
        <div class="card">
         <div class="card-image waves-effect waves-block waves-light">
           <img class="activator#" src="<%= galery.imagem.url(:medium) %>" style="padding:10px">
         </div>
         <%if current_user.user_type==1%>
         <div class="card-content">
           <!-- <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span> -->
           <p>
             <%= link_to 'Ver', galery %> |
             <%= link_to 'Editar', edit_galery_path(galery) %> |
             <%= link_to 'Apagar', galery, method: :delete, data: { confirm: 'Are you sure?' } %>
           </p>
         </div>
         <%end%>
         <div class="card-reveal">
           <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
           <!-- <p>Here is some more information about this product that is only revealed once clicked on.</p> -->
         </div>
       </div>
     </div>
    <% end %>
  </div>
<%= will_paginate @collection %>
<br>
<%if current_user.user_type == 1%>
<div class="fixed-action-btn vertical ">
  <a href="/galeries/new" class="btn-floating btn-large waves-effect waves-light green right"><i class="material-icons">add</i></a>
</div>
<%end%>
<!-- <%= link_to 'New Galery', new_galery_path %> -->

app/views/galeries/new.html.erb
<h1>Nova imagem para a galeria</h1>

<%= render 'form', galery: @galery %>

<%= link_to 'Voltar', galeries_path %>

app/views/galeries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <img src="<%= @galery.imagem.url(:thumb) %>">
</p>

<%= link_to 'Edit', edit_galery_path(@galery) %> |
<%= link_to 'Back', galeries_path %>