config/routes.rb
Rails.application.routes.draw do
  root "home#blog"
  resources :galeries
  resources :admins
  resources :modalidades
  resources :professors
  resources :atleta
  # devise_for :users
  devise_for :users, skip: [:registrations]
  as :user do
    # root "home#index"
    get "amif" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/home', to: 'home#index'
  get 'profile/:id', to: 'admins#edit'
  post '/saveFrontPanel/:id', to: 'home#saveFrontPanel'
  get '/blog', to: 'home#blog'
  #resources :dailies
  get '/dailies', to: 'dailies#index'
  post '/dailies', to: 'dailies#create'
  get '/dailies/new', to: 'dailies#new'
  get 'edit/dailies', to: 'dailies#edit'
  get '/dailies/reports', to: 'dailies#reports'
  post '/dailies/reports', to: 'dailies#reports_list'
  # post '/dailies_chamada', to: 'dailies#chamada'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  def bgImages
    @bgModals = []
    Modalidade.all.order('id asc').each do |z|
      @bgModals.push({id: z.id,imagem: z.imagem.url(:original)})
    end
    @bgModals.to_json.to_s.html_safe
  end
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all  if current_user.user_type == 1
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new if current_user.user_type == 1
    @bgModals = bgImages()
    @users = User.all
    @modalidade = Modalidade.all
  end

  # GET /professors/1/edit
  def edit
    @bgModals = bgImages()
    @users = User.all
    @modalidade = Modalidade.all
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params) if current_user.user_type == 1

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    if current_user.user_type == 1
      respond_to do |format|
        if @professor.update(professor_params)
          format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
          format.json { render :show, status: :ok, location: @professor }
        else
          format.html { render :edit }
          format.json { render json: @professor.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy if current_user.user_type == 1
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :sobrenome, :modalidades_id, :graduacao,:users_id)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<div class="bgProfessor">
    <%= form_for(professor) do |f| %>
      <% if professor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

          <ul>
          <% professor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col s6">
          <%= f.label :nome %>
          <%= f.text_field :nome %>
        </div>

        <div class="col s6">
          <%= f.label :sobrenome %>
          <%= f.text_field :sobrenome %>
        </div>
      </div>
      <div class="row">
        <div class="col s4">
          <%= f.label :modalidade %>
            <select name="professor[modalidades_id]" id="select_modal">
              <%@modalidade.each do |m|%>
              <option value="<%=m.id%>" <%="selected" if @professor.modalidades_id == m.id%>> <%=m.nome%></option>
              <%end%>
            </select>
        </div>

        <div class="col s4">
          <%= f.label :graduacao %>
          <%= f.text_field :graduacao %>
        </div>
        <div class="col s4">
          <%=f.label :users, 'Associado ao usuário', class:'red white-text '%>
          <select name="professor[users_id]" id="select_user">
            <%@users.each do |user|%>
            <option value="<%=user.id%>" <%="selected" if @professor.users_id == user.id%>><%=user.nome%></option>
            <%end%>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col s6">

          <%= f.submit "Salvar", class: "btn waves waves-effect" %>
        </div>
      </div>
    <% end %>
</div>

app/views/professors/edit.html.erb
<div class="container">
  
<%= link_to 'Voltar', professors_path %> |
<%= link_to 'Ver', @professor %>
<h1>Editar professor</h1>
<%= render 'form', professor: @professor %>

</div>

app/views/professors/index.html.erb
<div class="container">

  <h1>Professores</h1>

  <table class="striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Modalidade</th>
        <th>Graduação</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @professors.each do |professor| %>
        <tr>
          <td><%= professor.nome %></td>
          <td><%= professor.sobrenome %></td>
          <td><%= Modalidade.find_by_id(professor.modalidades_id).nome if Modalidade.find_by_id(professor.modalidades_id) != nil%></td>
          <td><%= professor.graduacao %></td>
          <td><%= link_to 'Ver', professor %></td>
          <td><%= link_to 'Editar', edit_professor_path(professor) %></td>
          <!-- <td><%= link_to 'Excluir', professor, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td> -->
          <td><%= link_to 'Desabilitar', "/professors/disable/#{professor.id}"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="fixed-action-btn vertical ">
    <a href="/professors/new" class="btn-floating btn-large waves-effect waves-light green right"><i class="material-icons">add</i></a>
  </div>
</div>

app/views/professors/new.html.erb
<div class="bgProfessor">
<div class="container">
<h1>Novo Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>
</div>
</div>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12 m4">
    <div class="card amber lighten-3">
      <div class="card-content black-text">
        <span class="card-title"><b>Ficha do professor</b></span>
          <p>
            <strong>Nome:</strong>
            <%= @professor.nome %>
          </p>

          <p>
            <strong>Sobrenome:</strong>
            <%= @professor.sobrenome %>
          </p>

          <p>
            <strong>Modalidade:</strong>
            <%= Modalidade.find_by_id(@professor.modalidades_id).nome %>
          </p>

          <p>
            <strong>Graduacao:</strong>
            <%= @professor.graduacao %>
          </p>
        </div>
      <div class="card-action">
        <%= link_to 'Voltar', professors_path, class:"blue-text" %> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Editar', edit_professor_path(@professor), class:"green-text" %>
      </div>
    </div>
  </div>
</div>