config/routes.rb
Rails.application.routes.draw do
  root "home#blog"
  resources :galeries
  resources :admins
  resources :modalidades
  resources :professors
  resources :atleta
  # devise_for :users
  devise_for :users, skip: [:registrations]
  as :user do
    # root "home#index"
    get "amif" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/home', to: 'home#index'
  get 'profile/:id', to: 'admins#edit'
  post '/saveFrontPanel/:id', to: 'home#saveFrontPanel'
  get '/blog', to: 'home#blog'
  #resources :dailies
  get '/dailies', to: 'dailies#index'
  post '/dailies', to: 'dailies#create'
  get '/dailies/new', to: 'dailies#new'
  get 'edit/dailies', to: 'dailies#edit'
  get '/dailies/reports', to: 'dailies#reports'
  post '/dailies/reports', to: 'dailies#reports_list'
  # post '/dailies_chamada', to: 'dailies#chamada'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
  has_attached_file :imagem,
    :url=>"/modalidades/images/:hash.:extension",
    :hash_secret=>"longSecretString",
    :styles=> {original: "780x567>"}
  validates_attachment_content_type :imagem, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_modalidade, only: [:show, :edit, :update, :destroy]

  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all if current_user.user_type == 1
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new if current_user.user_type == 1
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params) if current_user.user_type == 1

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully created.' }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1
  # PATCH/PUT /modalidades/1.json
  def update
    if current_user.user_type == 1
      respond_to do |format|
        if @modalidade.update(modalidade_params)
          format.html { redirect_to @modalidade, notice: 'Modalidade was successfully updated.' }
          format.json { render :show, status: :ok, location: @modalidade }
        else
          format.html { render :edit }
          format.json { render json: @modalidade.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade.destroy if current_user.user_type == 1
    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: 'Modalidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modalidade_params
      params.require(:modalidade).permit(:nome,:imagem)
    end
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/views/modalidades/_form.html.erb
<div class="container">
<%= form_for(modalidade) do |f| %>
  <% if modalidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
      <% modalidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col s4">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  <div class="col s4">
    <div class="file-field input-field">
      <div class="btn">
        <span>Anexar foto</span>
        <%=f.file_field :imagem%>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s4">
    <%= f.submit "Salvar",class:"btn waves waves-effect"%>
  </div>
</div>
</div>
<% end %>

app/views/modalidades/edit.html.erb
<div style="margin-left:200px">
<%= link_to 'Voltar', modalidades_path %> |
<%= link_to 'Ver', @modalidade %>
</div>
<h1 style="margin-left:200px">Editar Modalidade</h1>

<%= render 'form', modalidade: @modalidade %>

app/views/modalidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="margin-left:200px">Modalidades</h1>

<table class="striped container">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modalidades.each do |modalidade| %>
      <tr>
        <td><%= modalidade.nome %></td>
        <td><%= link_to 'Ver', modalidade %></td>
        <td><%= link_to 'Editar', edit_modalidade_path(modalidade) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="fixed-action-btn vertical ">
  <a href="/modalidades/new" class="btn-floating btn-large waves-effect waves-light green right"><i class="material-icons">add</i></a>
</div>

app/views/modalidades/new.html.erb
<h1>Nova modalidade</h1>

<%= render 'form', modalidade: @modalidade %>

<%= link_to 'Voltar', modalidades_path %>

app/views/modalidades/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col s12 m4">
    <div class="card amber lighten-3">
      <div class="card-content black-text">
        <span class="card-title"><b>Ficha do professor</b></span>
          <p>
            <strong>Nome:</strong>
            <%= @modalidade.nome %>
          </p>
          <div class="card-action">
            <%= link_to 'Voltar', modalidades_path, class:"blue-text" %> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to 'Editar', edit_modalidade_path(@modalidade), class:"green-text" %>
          </div>
      </div>
   </div>
</div>